### ISSUE TITLE
velero-volume-controller pods failed with Error loading veleroVolumeConfig 

### ISSUE THREAD

**Issue by sreesanpd** [duyanghao/velero-volume-controller#13]
When I tried to run velero-volume-config image, I'm getting the following error: 

```
$kubectl logs velero-volume-controller-84d55645b-7gdg6 F0825 10:40:04.323837       
1 main.go:50] Error loading veleroVolumeConfig: Failed to parse configuration,error: yaml: line 11: did not find expected alphabetic or numeric character
```

```
$kubectl describe pod velero-volume-controller-84d55645b-7gdg6 
Warning  BackOff    13s (x2 over 14s)  kubelet, gke-gke-cluster1-default-pool-01c166e2-mhth  Back-off restarting failed container
```

```
$ kubectl get pods 
NAME                                                 READY   STATUS             RESTARTS   AGE velero-volume-controller-84d55645b-7gdg6             0/1     CrashLoopBackOff   1          10s velero-volume-controller-84d55645b-d522w             0/1     CrashLoopBackOff   1          10s velero-volume-controller-84d55645b-wz4t2             0/1     CrashLoopBackOff   1          10s
```

```
$ cat examples/config.yaml
clusterServerCfg:
  masterURL:
  kubeConfig:
  leaseLockNamespace: velero
  leaseLockName: velero-volume-controller
veleroVolumeCfg:
  includeNamespaces:
  excludeNamespaces:
  includeVolumeTypes: persistentVolumeClaim
  excludeVolumeTypes:
  excludeJobs: *
```

```
$ kubectl describe cm
Name:         velero-volume-controller
Namespace:    default
Labels:       <none>
Annotations:
Data
====
config.yml:
----
clusterServerCfg:
  masterURL:
  kubeConfig:
  leaseLockNamespace: velero
  leaseLockName: velero-volume-controller
veleroVolumeCfg:
  includeNamespaces:
  excludeNamespaces:
  includeVolumeTypes: persistentVolumeClaim
  excludeVolumeTypes: gcePersistentDisk
  excludeJobs: *

Events:  <none>
```

One of the line which I found interesting while building the docker image: 

`Step 18/19 : COPY examples /velero-volume-controller/examples ---> 7f48a1722494 Step 19/19 : ENTRYPOINT ["./velero-volume-controller", "-c", "/velero-volume-controller/examples/config.yml", "-v", "4", "-logtostderr", "true"] ---> Running in 02305918bbfb Removing intermediate container 02305918bbfb ---> 603df5d60423 Successfully built 603df5d60423`

It is actually trying to create entrypoint with examples/config.yml while we actually have config.YAML

I have created the docker image by running "make dockerfiles.build". This image has been pushed to my private gcr repo and being used.

When I tried to run it outside kubernetes cluster, I'm getting the below error: 

```
$ bash hack/start.sh
Start velero-volume-controller now ...
cd cmd/controller && GO111MODULE=on go build -mod=vendor -v -o ../.././build/velero-volume-controller/velero-volume-controller
build github.com/google/uuid: cannot load github.com/google/uuid: open /tmp/velero-volume-controller/vendor/github.com/google/uuid: no such file or
directory
make: *** [Makefile:38: src.build] Error 1
```

I'm running these commands in google cloud shell (if that helps)

**Comment by duyanghao** [comment]
@sreesanpd I have fixed this bug in master branch, and please try with the latest commit : )

**Comment by sreesanpd** [comment]
Thanks for the quick update @duyanghao . I tried using the latest commit. I got a mixed result. 

Two replicas failed with the following error: 

```
$ kubectl logs velero-volume-controller-84d55645b-rdrwx F0901 08:29:14.340476       
1 main.go:50] Error loading veleroVolumeConfig: Failed to read configuration file: /velero-volume-controller/examples/config.yaml,error: open /velero-volume-controller/examples/config.yaml: no such file or directory
```

While one replica ran successfully but with following error (some times all the replicas failed with above error) : 

```
$ kubectl logs velero-volume-controller-84d55645b-dzt8m W0901 08:52:03.757914       
1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work. I0901 08:52:03.759517       1 leaderelection.go:242] attempting to acquire leader lease  velero/velero-volume-controller... E0901 08:52:03.769194       1 leaderelection.go:320] error retrieving resource lock velero/velero-volume-controller: leases.coordination.k8s.io "velero-volume-controller" is forbidden: User "system:serviceaccount:default:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "velero"
```

I'm using Google Kubernetes Engine.

**Comment by duyanghao** [comment]
@sreesanpd Please follow these steps to deploy velero-volume-controller:
```
# Generated image
$ make dockerfiles.build
# Retag and push to your docker registry
$ docker tag duyanghao/velero-volume-controller:v2.0 xxx/duyanghao/velero-volume-controller:v2.0
$ docker push xxx/duyanghao/velero-volume-controller:v2.0
# Update the deployment 'Image' field with the built image name
$ sed -i 's|REPLACE_IMAGE|xxx/duyanghao/velero-volume-controller:v2.0|g' examples/deployment/velero-volume-controller.yaml
# Create ClusterRole and ClusterRoleBinding
$ kubectl apply -f examples/deployment/cluster-role.yaml
$ kubectl apply -f examples/deployment/cluster-role-binding.yaml
# Create ConfigMap
$ kubectl apply -f examples/deployment/configmap.yaml
# Create velero-volume-controller deployment
$ kubectl apply -f examples/deployment/velero-volume-controller.yaml
```

**Comment by sreesanpd** [comment]
@duyanghao I'm following the exact steps that you have mentioned. I'm still having the above issue. 

Only one replica is running but with the error: 

`1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work. I0901 08:52:03.759517       1 leaderelection.go:242] attempting to acquire leader lease  velero/velero-volume-controller... E0901 08:52:03.769194       1 leaderelection.go:320] error retrieving resource lock velero/velero-volume-controller: leases.coordination.k8s.io "velero-volume-controller" is forbidden: User "system:serviceaccount:default:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "velero"`

Other two replicas are failed to start with the error: 

`1 main.go:50] Error loading veleroVolumeConfig: Failed to read configuration file: /velero-volume-controller/examples/config.yaml,error: open /velero-volume-controller/examples/config.yaml: no such file or directory
`

Is it some thing related to failure in getting leaselock on Google Kubernetes Engine (GKE) clusters by the velero-volume-controller pods?

**Comment by duyanghao** [comment]
@sreesanpd Thank for your feedback, please try with the latest master branch, I have fixed this bug and added podAntiAffinity feature for `velero-volume-controller`:
```
$ kubectl apply -f examples/deployment/cluster-role.yaml
$ kubectl apply -f examples/deployment/cluster-role-binding.yaml
# Create ConfigMap
$ kubectl apply -f examples/deployment/configmap.yaml -nvelero
# Create velero-volume-controller deployment
$ kubectl apply -f examples/deployment/velero-volume-controller.yaml -nvelero
```
And feel free to come back again if this problem remains.

**Comment by sreesanpd** [comment]
@duyanghao I have tried it with the latest master branch and I can confirm that it is working like a charm with google kubernetes engine (GKE)...thanks for the fix..closing this issue
